# Generated by Django 5.0 on 2024-05-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shippingCode',
        ),
    ]
