# Generated by Django 5.0 on 2024-03-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productStatus',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Modified'), (3, 'Passive')], default=1),
        ),
    ]
